name: Deploy test
on:
  push:
    branches: [main,develop,product]
  pull_request: 
    branches: [main,develop,product]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy: 
    matrix:
    node: [14,16,18]
    name: Node.js ${(matrix.node)} version 
    steps: 
        -name: check repo 
         uses: action/checkout@ V2 
        -name: setup node version ${(matrix.node-version)}
         uses: action/checkout@ V1 
 
        -run: npm install
        -run: npm run build  

